name: Build and Publish Chrome Extension

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.5
  workflow_dispatch:  # Allow manual trigger
    inputs:
      publish:
        description: 'Publish to Chrome Web Store'
        required: true
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Lint code
      run: npm run lint
      
    - name: Build extension
      run: npm run build
      
    - name: Verify build output
      run: |
        echo "Build output:"
        ls -la dist/
        echo "Manifest version:"
        cat dist/manifest.json | grep '"version"'
        
    - name: Create extension zip
      run: |
        cd dist
        zip -r ../extension-${{ github.ref_name || 'manual' }}.zip .
        cd ..
        echo "Extension zip created:"
        ls -la extension-*.zip
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: extension-build
        path: |
          extension-*.zip
          dist/
        retention-days: 30

  publish:
    needs: build
    runs-on: ubuntu-latest
    if: |
      (startsWith(github.ref, 'refs/tags/v') || 
       (github.event_name == 'workflow_dispatch' && github.event.inputs.publish == 'true'))
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: extension-build
        
    - name: Upload to Chrome Web Store
      uses: mnao305/chrome-extension-upload@v5.0.0
      with:
        file-path: extension-${{ github.ref_name || 'manual' }}.zip
        extension-id: ${{ secrets.CHROME_EXTENSION_ID }}
        client-id: ${{ secrets.CHROME_CLIENT_ID }}
        client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
        refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
        publish: true  # Automatically publish after upload
        
    - name: Create GitHub Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v2
      with:
        files: extension-${{ github.ref_name }}.zip
        generate_release_notes: true
        draft: false
        prerelease: false
        body: |
          ## 🚀 Mark-It-CE ${{ github.ref_name }}
          
          This release has been automatically published to the Chrome Web Store.
          
          ### 📦 Installation
          - Install from [Chrome Web Store](https://chromewebstore.google.com/detail/mark-it-memory-manager/ggpbonlpbpoimehcopnkeoklajdpkbho)
          - Or download the extension zip file below for manual installation
          
          ### 🔄 Changes
          See the [Release Notes](https://github.com/BotleApps/Mark-It-CE#-release-notes) for detailed changes.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  notify:
    needs: [build, publish]
    runs-on: ubuntu-latest
    if: always()
    
    steps:
    - name: Notify Success
      if: needs.publish.result == 'success'
      run: |
        echo "✅ Successfully published ${{ github.ref_name || 'manual build' }} to Chrome Web Store!"
        
    - name: Notify Failure
      if: needs.publish.result == 'failure' || needs.build.result == 'failure'
      run: |
        echo "❌ Failed to publish extension. Check the logs for details."
        exit 1
